/**
 * ArUco Dictionary implementation.
 *
 * Marker bit patterns are sourced from ACTUAL OpenCV predefined dictionary data
 * (extracted from OpenCV 5.x bytesList). This guarantees exact compatibility
 * with cv2.aruco.getPredefinedDictionary() — markers will be correctly detected
 * by OpenCV's detectMarkers().
 *
 * Dictionary data lives in arucoDictData.ts (auto-generated by
 * scripts/extract_aruco_dicts.py). For custom dictionaries not in the
 * predefined set, an OpenCV-compatible extendDictionary algorithm is used as
 * fallback.
 *
 * Layout per OpenCV bytesList: [marker_id][rotation][byte]
 * - 4 rotations per marker (0°, 90°, 180°, 270° clockwise)
 * - ceil(markerSize²/8) bytes per rotation
 * - Bits within each byte are MSB-first (bit 7 = first pixel of the row)
 */

import {
  ARUCO_DICT_DATA,
  extractMarkerBits,
} from './arucoDictData';

export type DictSize = 4 | 5 | 6 | 7;

export interface ArucoDictionary {
  name: string;
  markerSize: DictSize;
  nMarkers: number;
  /** Flat bytesList data matching OpenCV format, or empty if fallback-generated */
  bytes: Uint8Array;
  bytesPerMarker: number;
  maxCorrection: number;
}

// ─── Seeded PRNG (Mulberry32) ────────────────────────────────────────────────
// Used ONLY for fallback custom dictionary generation.

function mulberry32(seed: number): () => number {
  return () => {
    seed |= 0;
    seed = seed + 0x6D2B79F5 | 0;
    let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

// ─── Hamming Distance ────────────────────────────────────────────────────────

function hamming(a: number[][], b: number[][]): number {
  let d = 0;
  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < a[i].length; j++) {
      if (a[i][j] !== b[i][j]) d++;
    }
  }
  return d;
}

function rotate90(marker: number[][]): number[][] {
  const n = marker.length;
  const result: number[][] = Array.from({ length: n }, () => Array(n).fill(0));
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      result[j][n - 1 - i] = marker[i][j];
    }
  }
  return result;
}

function minSelfDistance(marker: number[][]): number {
  let minD = Infinity;
  let rot = marker;
  for (let r = 1; r < 4; r++) {
    rot = rotate90(rot);
    const d = hamming(marker, rot);
    if (d < minD) minD = d;
  }
  return minD;
}

// ─── OpenCV's exact tau calculation ──────────────────────────────────────────
// From OpenCV 4.x aruco_dictionary.cpp:
//   float C = (float)(markerSize * markerSize) / 4.f;
//   int tau = 2 * (int)(C * 4.f / 3.f);

function openCvTau(markerSize: number): number {
  const C = markerSize * markerSize / 4;
  return 2 * Math.floor(C * 4 / 3);
}

// ─── Fallback: OpenCV-compatible extendDictionary algorithm ──────────────────
// Implements the same algorithm as OpenCV's extendDictionary() for generating
// custom dictionaries. Uses a seeded RNG for reproducibility.

const fallbackCache = new Map<string, number[][][]>();

function generateMarkersFallback(
  markerSize: DictSize,
  nMarkers: number,
  seed: number = 0,
): number[][][] {
  const cacheKey = `${markerSize}x${markerSize}_${nMarkers}_s${seed}`;
  if (fallbackCache.has(cacheKey)) return fallbackCache.get(cacheKey)!;

  const markers: number[][][] = [];
  let tau = openCvTau(markerSize);
  const rng = mulberry32(seed);
  const maxUnproductive = 5000;

  while (markers.length < nMarkers && tau > 0) {
    let bestTau = 0;
    let bestMarker: number[][] | null = null;
    let attempts = 0;

    while (attempts < maxUnproductive) {
      attempts++;

      // Generate random marker
      const candidate: number[][] = Array.from({ length: markerSize }, () =>
        Array.from({ length: markerSize }, () => Math.floor(rng() * 2)),
      );

      // Self-distance (rotation invariance)
      const selfDist = minSelfDistance(candidate);

      // Inter-marker distance (min Hamming to existing markers)
      const interDist = markers.length > 0
        ? Math.min(...markers.map(m => hamming(candidate, m)))
        : Infinity;

      const currentTau = Math.min(selfDist, interDist);

      if (currentTau > bestTau) {
        bestTau = currentTau;
        bestMarker = candidate;
        attempts = 0; // reset counter on improvement (matching OpenCV behavior)
        if (currentTau >= tau) break;
      }
    }

    if (bestMarker && bestTau >= tau) {
      markers.push(bestMarker);
    } else {
      tau--; // Reduce threshold (matching OpenCV behavior)
    }
  }

  if (markers.length < nMarkers) {
    // This shouldn't happen for reasonable parameters, but warn if it does
    console.warn(
      `[arucoDictionaries] Only generated ${markers.length}/${nMarkers} markers ` +
      `for ${markerSize}x${markerSize} (final tau=${tau}). Increase nMarkers or use a different size.`,
    );
  }

  fallbackCache.set(cacheKey, markers);
  return markers;
}

// ─── Get Marker Bit Matrix ───────────────────────────────────────────────────
// Primary: use hardcoded OpenCV data.
// Fallback: use OpenCV-compatible algorithm.

const bitCache = new Map<string, number[][]>();

export function getMarkerBits(dict: ArucoDictionary, markerId: number): number[][] {
  const cacheKey = `${dict.name}_${markerId}`;
  if (bitCache.has(cacheKey)) return bitCache.get(cacheKey)!.map(row => [...row]);

  let matrix: number[][] | null = null;

  // Try hardcoded data first
  const bytesEntry = ARUCO_DICT_DATA[dict.name];
  if (bytesEntry) {
    matrix = extractMarkerBits(
      bytesEntry.data,
      markerId,
      bytesEntry.markerSize as DictSize,
      bytesEntry.bytesPerMarker,
    );
  }

  // Fallback to algorithm generation
  if (!matrix) {
    const markers = generateMarkersFallback(dict.markerSize, dict.nMarkers);
    const idx = markerId % markers.length;
    matrix = markers[idx].map(row => [...row]);
  }

  bitCache.set(cacheKey, matrix.map(row => [...row]));
  return matrix.map(row => [...row]);
}

// ─── Get Full Marker Image (with border) ─────────────────────────────────────

export function getMarkerImage(
  dict: ArucoDictionary,
  markerId: number,
  cellSize: number,
): { matrix: number[][]; pixelSize: number } {
  const bits = getMarkerBits(dict, markerId);
  const borderBits = 1;
  const matrixSize = dict.markerSize + 2 * borderBits;
  const pixelSize = matrixSize * cellSize;

  const matrix: number[][] = Array.from({ length: matrixSize }, (_, i) =>
    Array.from({ length: matrixSize }, (_, j) => {
      if (
        i < borderBits || i >= matrixSize - borderBits ||
        j < borderBits || j >= matrixSize - borderBits
      ) {
        return 1; // Border (black)
      }
      return bits[i - borderBits][j - borderBits];
    }),
  );

  return { matrix, pixelSize };
}

// ─── Create / Get Dictionary ─────────────────────────────────────────────────

const dictRegistry = new Map<string, ArucoDictionary>();

export function getDictionary(name: string): ArucoDictionary {
  if (dictRegistry.has(name)) return dictRegistry.get(name)!;

  const match = name.match(/DICT_(\d+)X\d+_(\d+)/);
  if (!match) throw new Error(`Invalid dictionary name: ${name}`);

  const markerSize = parseInt(match[1]) as DictSize;
  const nMarkers = parseInt(match[2]);
  const bitsPerMarker = markerSize * markerSize;
  const bytesPerMarker = Math.ceil(bitsPerMarker / 8);

  // Load bytes from hardcoded data if available
  let bytes: Uint8Array = new Uint8Array(0);
  const bytesEntry = ARUCO_DICT_DATA[name];
  if (bytesEntry) {
    bytes = Uint8Array.from(bytesEntry.data);
  }

  const dict: ArucoDictionary = {
    name,
    markerSize,
    nMarkers,
    bytes,
    bytesPerMarker,
    maxCorrection: Math.floor(bitsPerMarker / 8),
  };

  dictRegistry.set(name, dict);
  return dict;
}

// ─── Render Helper ───────────────────────────────────────────────────────────

export function renderMarkerOnCanvas(
  ctx: CanvasRenderingContext2D,
  dict: ArucoDictionary,
  markerId: number,
  x: number,
  y: number,
  cellSize: number,
  color: string = '#000000',
): void {
  const { matrix, pixelSize } = getMarkerImage(dict, markerId, cellSize);

  ctx.fillStyle = color;
  for (let i = 0; i < matrix.length; i++) {
    for (let j = 0; j < matrix[i].length; j++) {
      if (matrix[i][j] === 1) {
        ctx.fillRect(x + j * cellSize, y + i * cellSize, cellSize, cellSize);
      }
    }
  }
}
