/**
 * End-to-end OpenCV compatibility test.
 *
 * Renders single markers AND a full SVG board with the website's own
 * generators, rasterises them to pixels, then runs them through the REAL
 * OpenCV ArUco detector via a Python helper. This is the acceptance test
 * for the goal: "board generated by website must work in OpenCV".
 *
 * The Python helper (scripts/e2e_detect.py) must exist; the test is skipped
 * with a clear message when opencv-python is not installed.
 */
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { writeFileSync, unlinkSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { getDictionary, getMarkerBits } from '../arucoDictionaries';
import { generateSvg } from '../svgGenerator';

const HELPER = join(__dirname, '..', '..', 'scripts', 'e2e_detect.py');

function opencvAvailable(): boolean {
  try {
    execFileSync('python', ['-c', 'import cv2'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/** Render a getMarkerBits matrix (1=black) to a grayscale PGM buffer. */
function markerToPgm(
  bits: number[][],
  dictName: string,
  markerId: number,
  cellPx = 20,
): { path: string; cleanup: () => void } {
  const inner = bits.length;
  const total = inner + 2; // 1-bit black border
  const size = total * cellPx;
  const px = new Uint8Array(size * size).fill(255);
  for (let r = 0; r < total; r++) {
    for (let c = 0; c < total; c++) {
      const black =
        r === 0 || r === total - 1 || c === 0 || c === total - 1
          ? true
          : bits[r - 1][c - 1] === 1;
      if (black) {
        for (let y = r * cellPx; y < (r + 1) * cellPx; y++) {
          for (let x = c * cellPx; x < (c + 1) * cellPx; x++) {
            px[y * size + x] = 0;
          }
        }
      }
    }
  }
  // Quiet-zone margin so the detector sees an isolated marker
  const margin = cellPx * 2;
  const full = size + margin * 2;
  const fullPx = new Uint8Array(full * full).fill(255);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      fullPx[(y + margin) * full + (x + margin)] = px[y * size + x];
    }
  }
  const header = Buffer.from(`P5\n${full} ${full}\n255\n`, 'ascii');
  const out = Buffer.concat([header, Buffer.from(fullPx)]);
  const path = join(tmpdir(), `e2e-marker-${Date.now()}-${markerId}.pgm`);
  writeFileSync(path, out);
  void dictName;
  return { path, cleanup: () => { try { unlinkSync(path); } catch { /* noop */ } } };
}

function detectMarker(pgmPath: string, dictName: string): number[] {
  const out = execFileSync(
    'python',
    [HELPER, 'marker', pgmPath, dictName],
    { encoding: 'utf-8' },
  );
  return JSON.parse(out) as number[];
}

describe('OpenCV end-to-end: website markers are detectable', () => {
  const run = opencvAvailable() && existsSync(HELPER);

  it.each([
    ['DICT_4X4_50', 0],
    ['DICT_4X4_50', 1],
    ['DICT_5X5_100', 0],
    ['DICT_5X5_100', 1],
    ['DICT_6X6_250', 0],
    ['DICT_6X6_250', 1],
    ['DICT_7X7_50', 0],
    ['DICT_7X7_50', 1],
  ] as Array<[string, number]>)(
    '%s marker %d detected with correct id',
    (dictName, id) => {
      if (!run) return; // skip without opencv
      const dict = getDictionary(dictName);
      const bits = getMarkerBits(dict, id);
      const { path, cleanup } = markerToPgm(bits, dictName, id);
      try {
        const ids = detectMarker(path, dictName);
        expect(ids).toContain(id);
      } finally {
        cleanup();
      }
    },
  );
});

describe('OpenCV end-to-end: full SVG board is detectable', () => {
  it('4x3 DICT_4X4_50 board detects all 6 markers with sequential ids', () => {
    if (!opencvAvailable() || !existsSync(HELPER)) return;
    const svg = generateSvg(
      {
        squaresX: 4,
        squaresY: 3,
        squareLength: 40,
        markerLength: 24,
        margin: 0,
        dictionary: 'DICT_4X4_50',
      } as never,
      true,
    );
    const path = join(tmpdir(), `e2e-board-${Date.now()}.svg`);
    writeFileSync(path, svg, 'utf-8');
    try {
      const out = execFileSync(
        'python',
        [HELPER, 'board', path, 'DICT_4X4_50', '4', '3', '40', '24'],
        { encoding: 'utf-8', maxBuffer: 16 * 1024 * 1024 },
      );
      const res = JSON.parse(out) as { ids: number[]; charucoCorners: number };
      expect(res.ids.sort((a, b) => a - b)).toEqual([0, 1, 2, 3, 4, 5]);
      expect(res.charucoCorners).toBeGreaterThan(0);
    } finally {
      try { unlinkSync(path); } catch { /* noop */ }
    }
  });
});
