#!/usr/bin/env python3
"""
extract_aruco_dicts.py — Extract actual OpenCV ArUco dictionary bytesList data
and output as a TypeScript source file.

Usage:
    python scripts/extract_aruco_dicts.py > lib/arucoDictData.ts

Output: TypeScript file with Uint8Array data for all 16 predefined dictionaries.
"""
import cv2
import sys
import io

# ─── Dictionary mapping ───
DICT_NAMES = [
    ("DICT_4X4_50", cv2.aruco.DICT_4X4_50),
    ("DICT_4X4_100", cv2.aruco.DICT_4X4_100),
    ("DICT_4X4_250", cv2.aruco.DICT_4X4_250),
    ("DICT_4X4_1000", cv2.aruco.DICT_4X4_1000),
    ("DICT_5X5_50", cv2.aruco.DICT_5X5_50),
    ("DICT_5X5_100", cv2.aruco.DICT_5X5_100),
    ("DICT_5X5_250", cv2.aruco.DICT_5X5_250),
    ("DICT_5X5_1000", cv2.aruco.DICT_5X5_1000),
    ("DICT_6X6_50", cv2.aruco.DICT_6X6_50),
    ("DICT_6X6_100", cv2.aruco.DICT_6X6_100),
    ("DICT_6X6_250", cv2.aruco.DICT_6X6_250),
    ("DICT_6X6_1000", cv2.aruco.DICT_6X6_1000),
    ("DICT_7X7_50", cv2.aruco.DICT_7X7_50),
    ("DICT_7X7_100", cv2.aruco.DICT_7X7_100),
    ("DICT_7X7_250", cv2.aruco.DICT_7X7_250),
    ("DICT_7X7_1000", cv2.aruco.DICT_7X7_1000),
]


def extract_bytes(name, enum_val):
    """Extract bytesList from a predefined dictionary."""
    dict_obj = cv2.aruco.getPredefinedDictionary(enum_val)
    bytes_list = dict_obj.bytesList  # shape: (nMarkers, bytesPerMarker, 4), CV_8UC4

    marker_size = int(name.split("_")[1].split("X")[0])
    bits_per_marker = marker_size * marker_size
    bytes_per_marker = (bits_per_marker + 7) // 8
    n_markers = int(name.split("_")[2])

    # CRITICAL: bytesList is a CV_8UC4 Mat with shape (nMarkers, bytesPerMarker, 4).
    # Rotation r's bytes are CONTIGUOUS in linear row memory:
    #   row.flatten() == [rot0 (bytesPerMarker B) | rot1 | rot2 | rot3].
    # Do NOT index the (byte, rotation) column (bytes_list[m, b, r]) — that reads
    # strided memory and produces transposed garbage. Flatten each marker row
    # in C order and store the blocks contiguously.
    import numpy as np
    flat = []
    for m_idx in range(n_markers):
        row = np.asarray(bytes_list[m_idx]).flatten().tolist()
        assert len(row) == 4 * bytes_per_marker, (
            f"{name} marker {m_idx}: expected {4 * bytes_per_marker} bytes, got {len(row)}"
        )
        flat.extend(int(v) for v in row)

    return flat, marker_size, n_markers, bytes_per_marker


def bytes_to_hex_array(data):
    """Convert a list of ints to TypeScript hex array string."""
    chunks = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_str = ",".join(f"0x{b:02x}" for b in chunk)
        chunks.append(hex_str)
    return ",\n  ".join(chunks)


def generate_ts():
    """Generate complete TypeScript source."""
    lines = []
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append("//  AUTO-GENERATED — DO NOT EDIT")
    lines.append("//  Generated by: scripts/extract_aruco_dicts.py")
    lines.append(f"//  OpenCV version: {cv2.__version__}")
    lines.append("//  Date: auto-generated")
    lines.append("//")
    lines.append("//  Contains ACTUAL OpenCV predefined dictionary bytesList data.")
    lines.append("//  These match cv2.aruco.getPredefinedDictionary() exactly.")
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append("")

    lines.append("// ─── Types ───────────────────────────────────────────────────")
    lines.append("")
    lines.append("export interface DictBytes {")
    lines.append("  name: string;")
    lines.append("  markerSize: number;")
    lines.append("  nMarkers: number;")
    lines.append("  bytesPerMarker: number;")
    lines.append('  /** Flat Uint8Array: [marker0_rot0_bytes..., marker0_rot1_bytes..., ...] */')
    lines.append("  data: Uint8Array;")
    lines.append("}")
    lines.append("")
    lines.append("// ─── Dictionary Data ─────────────────────────────────────────")
    lines.append("")

    # Generate each dictionary
    dict_objects = []
    for name, enum_val in DICT_NAMES:
        flat, marker_size, n_markers, bytes_per_marker = extract_bytes(name, enum_val)

        const_name = f"BYTES_{name}"  # e.g. BYTES_DICT_6X6_250
        lines.append(f"/** {name}: {n_markers} markers, {marker_size}x{marker_size}, {bytes_per_marker} B/rot × 4 rot */")
        lines.append(f"const {const_name}: Uint8Array = new Uint8Array([")
        lines.append(f"  {bytes_to_hex_array(flat)}")
        lines.append("]);")
        lines.append("")

        dict_objects.append((name, const_name, marker_size, n_markers, bytes_per_marker))

    # Generate the registry
    lines.append("// ─── Registry ────────────────────────────────────────────────")
    lines.append("")
    lines.append("export const ARUCO_DICT_DATA: Record<string, DictBytes> = {")
    for name, const_name, marker_size, n_markers, bytes_per_marker in dict_objects:
        lines.append(f'  "{name}": {{ name: "{name}", markerSize: {marker_size}, nMarkers: {n_markers}, bytesPerMarker: {bytes_per_marker}, data: {const_name} }},')
    lines.append("};")
    lines.append("")
    lines.append("/**")
    lines.append(" * Get marker bit matrix from dictionary data.")
    lines.append(" * Returns: number[][] where 1=black, 0=white")
    lines.append(" */")
    lines.append("export function getMarkerBitsFromBytes(")
    lines.append("  dictName: string,")
    lines.append("  markerId: number,")
    lines.append("): number[][] | null {")
    lines.append("  const entry = ARUCO_DICT_DATA[dictName];")
    lines.append("  if (!entry) return null;")
    lines.append("  return extractMarkerBits(entry.data, markerId, entry.markerSize, entry.bytesPerMarker);")
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Extract a single marker's bit matrix from bytesList data.")
    lines.append(" * Uses rotation 0 (no rotation).")
    lines.append(" *")
    lines.append(" * OpenCV convention: bit 1 = WHITE, bit 0 = BLACK (see")
    lines.append(" * Dictionary::generateImageMarker / getBitsFromByteList). This function")
    lines.append(" * returns 1=BLACK, 0=WHITE (inverted), matching the renderers which")
    lines.append(" * paint a cell black when the value is 1.")
    lines.append(" *")
    lines.append(" * The stored data is one marker row flattened in C order:")
    lines.append(" * [rot0 (bytesPerMarker B) | rot1 | rot2 | rot3]. For marker sizes")
    lines.append(" * whose bit count is not a multiple of 8, only the LOW (nBits % 8)")
    lines.append(" * bits of the last byte belong to the marker (high bits are padding).")
    lines.append(" */")
    lines.append("export function extractMarkerBits(")
    lines.append("  data: Uint8Array,")
    lines.append("  markerId: number,")
    lines.append("  markerSize: number,")
    lines.append("  bytesPerMarker: number,")
    lines.append("): number[][] {")
    lines.append("  const rotationBytes = 4 * bytesPerMarker;")
    lines.append("  const base = markerId * rotationBytes; // rotation 0 starts here")
    lines.append("")
    lines.append("  // Collect ALL bits MSB-first from the rot0 block ...")
    lines.append("  const allBits: number[] = [];")
    lines.append("  for (let b = 0; b < bytesPerMarker; b++) {")
    lines.append("    const byte = data[base + b];")
    lines.append("    for (let bitPos = 7; bitPos >= 0; bitPos--) {")
    lines.append("      allBits.push((byte >> bitPos) & 1);")
    lines.append("    }")
    lines.append("  }")
    lines.append("  // ... then take the FIRST nBits: floor(nBits/8) full bytes plus the")
    lines.append("  // LOW (nBits % 8) bits of the next byte (OpenCV getBitsFromByteList).")
    lines.append("  const nBits = markerSize * markerSize;")
    lines.append("  const fullBytes = Math.floor(nBits / 8);")
    lines.append("  const restBits = nBits % 8;")
    lines.append("  const markerBits = allBits.slice(0, fullBytes * 8);")
    lines.append("  if (restBits > 0) {")
    lines.append("    const tailByteStart = (fullBytes + 1) * 8 - restBits;")
    lines.append("    markerBits.push(...allBits.slice(tailByteStart, (fullBytes + 1) * 8));")
    lines.append("  }")
    lines.append("")
    lines.append("  // Invert: OpenCV 1=white -> renderer 1=black.")
    lines.append("  const matrix: number[][] = [];")
    lines.append("  for (let row = 0; row < markerSize; row++) {")
    lines.append("    const matrixRow: number[] = [];")
    lines.append("    for (let col = 0; col < markerSize; col++) {")
    lines.append("      matrixRow.push(markerBits[row * markerSize + col] === 1 ? 0 : 1);")
    lines.append("    }")
    lines.append("    matrix.push(matrixRow);")
    lines.append("  }")
    lines.append("  return matrix;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    ts_source = generate_ts()
    # Write directly to the output file to avoid encoding issues
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "..", "lib", "arucoDictData.ts")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(ts_source)
    print(f"Written to: {os.path.abspath(out_path)}", file=sys.stderr)
