#!/usr/bin/env python3
"""
extract_aruco_dicts.py — Extract actual OpenCV ArUco dictionary bytesList data
and output as a TypeScript source file.

Usage:
    python scripts/extract_aruco_dicts.py > lib/arucoDictData.ts

Output: TypeScript file with Uint8Array data for all 16 predefined dictionaries.
"""
import cv2
import sys
import io

# ─── Dictionary mapping ───
DICT_NAMES = [
    ("DICT_4X4_50", cv2.aruco.DICT_4X4_50),
    ("DICT_4X4_100", cv2.aruco.DICT_4X4_100),
    ("DICT_4X4_250", cv2.aruco.DICT_4X4_250),
    ("DICT_4X4_1000", cv2.aruco.DICT_4X4_1000),
    ("DICT_5X5_50", cv2.aruco.DICT_5X5_50),
    ("DICT_5X5_100", cv2.aruco.DICT_5X5_100),
    ("DICT_5X5_250", cv2.aruco.DICT_5X5_250),
    ("DICT_5X5_1000", cv2.aruco.DICT_5X5_1000),
    ("DICT_6X6_50", cv2.aruco.DICT_6X6_50),
    ("DICT_6X6_100", cv2.aruco.DICT_6X6_100),
    ("DICT_6X6_250", cv2.aruco.DICT_6X6_250),
    ("DICT_6X6_1000", cv2.aruco.DICT_6X6_1000),
    ("DICT_7X7_50", cv2.aruco.DICT_7X7_50),
    ("DICT_7X7_100", cv2.aruco.DICT_7X7_100),
    ("DICT_7X7_250", cv2.aruco.DICT_7X7_250),
    ("DICT_7X7_1000", cv2.aruco.DICT_7X7_1000),
]


def extract_bytes(name, enum_val):
    """Extract bytesList from a predefined dictionary."""
    dict_obj = cv2.aruco.getPredefinedDictionary(enum_val)
    bytes_list = dict_obj.bytesList  # shape: (nMarkers, bytesPerMarker, 4)

    marker_size = int(name.split("_")[1].split("X")[0])
    bits_per_marker = marker_size * marker_size
    bytes_per_marker = (bits_per_marker + 7) // 8
    n_markers = int(name.split("_")[2])

    # bytesList shape in OpenCV 5.x: (nMarkers, bytesPerMarker, 4)
    # where dimension 2 = 4 rotations (0, 90, 180, 270 clockwise)
    flat = []
    for m_idx in range(n_markers):
        for r_idx in range(4):
            for b_idx in range(bytes_per_marker):
                flat.append(int(bytes_list[m_idx, b_idx, r_idx]))

    return flat, marker_size, n_markers, bytes_per_marker


def bytes_to_hex_array(data):
    """Convert a list of ints to TypeScript hex array string."""
    chunks = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_str = ",".join(f"0x{b:02x}" for b in chunk)
        chunks.append(hex_str)
    return ",\n  ".join(chunks)


def generate_ts():
    """Generate complete TypeScript source."""
    lines = []
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append("//  AUTO-GENERATED — DO NOT EDIT")
    lines.append("//  Generated by: scripts/extract_aruco_dicts.py")
    lines.append(f"//  OpenCV version: {cv2.__version__}")
    lines.append("//  Date: auto-generated")
    lines.append("//")
    lines.append("//  Contains ACTUAL OpenCV predefined dictionary bytesList data.")
    lines.append("//  These match cv2.aruco.getPredefinedDictionary() exactly.")
    lines.append("// ═══════════════════════════════════════════════════════════════")
    lines.append("")

    lines.append("// ─── Types ───────────────────────────────────────────────────")
    lines.append("")
    lines.append("export interface DictBytes {")
    lines.append("  name: string;")
    lines.append("  markerSize: number;")
    lines.append("  nMarkers: number;")
    lines.append("  bytesPerMarker: number;")
    lines.append('  /** Flat Uint8Array: [marker0_rot0_bytes..., marker0_rot1_bytes..., ...] */')
    lines.append("  data: Uint8Array;")
    lines.append("}")
    lines.append("")
    lines.append("// ─── Dictionary Data ─────────────────────────────────────────")
    lines.append("")

    # Generate each dictionary
    dict_objects = []
    for name, enum_val in DICT_NAMES:
        flat, marker_size, n_markers, bytes_per_marker = extract_bytes(name, enum_val)

        const_name = f"BYTES_{name}"  # e.g. BYTES_DICT_6X6_250
        lines.append(f"/** {name}: {n_markers} markers, {marker_size}x{marker_size}, {bytes_per_marker} B/rot × 4 rot */")
        lines.append(f"const {const_name}: Uint8Array = new Uint8Array([")
        lines.append(f"  {bytes_to_hex_array(flat)}")
        lines.append("]);")
        lines.append("")

        dict_objects.append((name, const_name, marker_size, n_markers, bytes_per_marker))

    # Generate the registry
    lines.append("// ─── Registry ────────────────────────────────────────────────")
    lines.append("")
    lines.append("export const ARUCO_DICT_DATA: Record<string, DictBytes> = {")
    for name, const_name, marker_size, n_markers, bytes_per_marker in dict_objects:
        lines.append(f'  "{name}": {{ name: "{name}", markerSize: {marker_size}, nMarkers: {n_markers}, bytesPerMarker: {bytes_per_marker}, data: {const_name} }},')
    lines.append("};")
    lines.append("")
    lines.append("/**")
    lines.append(" * Get marker bit matrix from dictionary data.")
    lines.append(" * Returns: number[][] where 1=black, 0=white")
    lines.append(" */")
    lines.append("export function getMarkerBitsFromBytes(")
    lines.append("  dictName: string,")
    lines.append("  markerId: number,")
    lines.append("): number[][] | null {")
    lines.append("  const entry = ARUCO_DICT_DATA[dictName];")
    lines.append("  if (!entry) return null;")
    lines.append("  return extractMarkerBits(entry.data, markerId, entry.markerSize, entry.bytesPerMarker);")
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Extract a single marker's bit matrix from bytesList data.")
    lines.append(" * Uses rotation 0 (no rotation).")
    lines.append(" */")
    lines.append("export function extractMarkerBits(")
    lines.append("  data: Uint8Array,")
    lines.append("  markerId: number,")
    lines.append("  markerSize: number,")
    lines.append("  bytesPerMarker: number,")
    lines.append("): number[][] {")
    lines.append("  // OpenCV bytesList layout: [marker][rotation][byte]")
    lines.append("  // Each marker has 4 rotations, each rotation has bytesPerMarker bytes")
    lines.append("  const rotationBytes = 4 * bytesPerMarker;")
    lines.append("  const offset = markerId * rotationBytes;")
    lines.append("  // Use rotation 0 (first rotation)")
    lines.append("  const rotOffset = offset;")
    lines.append("")
    lines.append("  const matrix: number[][] = [];")
    lines.append("  let bitIdx = 0;")
    lines.append("  for (let row = 0; row < markerSize; row++) {")
    lines.append("    const matrixRow: number[] = [];")
    lines.append("    for (let col = 0; col < markerSize; col++) {")
    lines.append("      const byteIdx = rotOffset + Math.floor(bitIdx / 8);")
    lines.append("      const bitPos = bitIdx % 8;")
    lines.append("      const bit = (data[byteIdx] >> (7 - bitPos)) & 1;")
    lines.append("      matrixRow.push(bit);")
    lines.append("      bitIdx++;")
    lines.append("    }")
    lines.append("    matrix.push(matrixRow);")
    lines.append("  }")
    lines.append("  return matrix;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    ts_source = generate_ts()
    # Write directly to the output file to avoid encoding issues
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "..", "lib", "arucoDictData.ts")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(ts_source)
    print(f"Written to: {os.path.abspath(out_path)}", file=sys.stderr)
